version = 0.1

[default.deploy.parameters]
stack_name = "user-chat-ai-api"
resolve_s3 = true
s3_prefix = "user-chat-ai-api"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
